FROM php:8.1.3-fpm-alpine

RUN apk update; \
    apk upgrade;

RUN apk --no-cache add --virtual .build-deps $PHPIZE_DEPS \
        && apk --no-cache add --virtual .ext-deps \
        libzip-dev  \
        libpng-dev \
        libxslt-dev \
        imap-dev \
        zip \
        jpegoptim optipng pngquant gifsicle \
        unzip \
        bash \
        git \
        curl \
        wget \
        libzip  \
        libpng  \
        libjpeg-turbo \
        libwebp \
        freetype \
        libwebp-dev \
        libjpeg-turbo-dev \
        freetype-dev \
        postgresql-dev 
   
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp
RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql pcntl bcmath opcache gd zip
RUN apk del .build-deps

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#Add custom php ini setting to other settings
ADD ./docker/local/config/php/* /usr/local/etc/php/conf.d/

USER 1000


